# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yuino.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0byuino.proto\"G\n\tYuinoWord\x12\x0f\n\x07surface\x18\x01 \x01(\t\x12\x0c\n\x04read\x18\x02 \x01(\t\x12\x0e\n\x06vector\x18\x03 \x01(\r\x12\x0b\n\x03pos\x18\x04 \x01(\r\"#\n\x08YuinoPos\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03vec\x18\x02 \x01(\r\">\n\x08YuinoDic\x12\x19\n\x05words\x18\x01 \x03(\x0b\x32\n.YuinoWord\x12\x17\n\x04poss\x18\x02 \x03(\x0b\x32\t.YuinoPosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yuino_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _YUINOWORD._serialized_start=15
  _YUINOWORD._serialized_end=86
  _YUINOPOS._serialized_start=88
  _YUINOPOS._serialized_end=123
  _YUINODIC._serialized_start=125
  _YUINODIC._serialized_end=187
# @@protoc_insertion_point(module_scope)
